# Generated by Django 4.2.7 on 2024-01-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_ed', models.AutoField(primary_key=True, serialize=False)),
                ('region_ed', models.CharField(max_length=255)),
                ('nombre_ed', models.CharField(max_length=255)),
                ('capital_ed', models.CharField(max_length=255)),
            ],
        ),
    ]
