# Generated by Django 4.2.7 on 2024-01-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='prefijo_ed',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
