# Generated by Django 4.2.7 on 2024-01-16 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_provincia_prefijo_ed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_ed', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ed', models.CharField(max_length=255)),
                ('cedula_ed', models.CharField(max_length=15)),
                ('correo_ed', models.EmailField(max_length=254)),
                ('telefono_ed', models.CharField(max_length=15)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.provincia')),
            ],
        ),
    ]
