# Generated by Django 4.2.7 on 2024-01-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_ed',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_ed',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_ed',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento_ed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia_ed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.provincia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula_ed',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_ed',
            field=models.CharField(max_length=150),
        ),
    ]
