# Generated by Django 4.2.7 on 2024-01-16 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0004_remove_cliente_provincia_remove_cliente_telefono_ed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_ed', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ed', models.DateField()),
                ('estado_ed', models.CharField(max_length=50)),
                ('observaciones_ed', models.TextField()),
                ('cliente_ed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.cliente')),
            ],
        ),
    ]
