# Generated by Django 4.2.7 on 2024-01-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0005_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_ed', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ed', models.CharField(max_length=150)),
                ('descripcion_ed', models.TextField()),
                ('fotografia', models.FileField(blank=True, null=True, upload_to='tipo')),
            ],
        ),
    ]
