# Generated by Django 4.2.7 on 2024-01-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0006_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id_ed', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ed', models.CharField(max_length=100)),
                ('precio_ed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad_ed', models.CharField(max_length=50)),
                ('fotografia', models.FileField(blank=True, null=True, upload_to='platillo')),
                ('tipo_ed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.tipo')),
            ],
        ),
    ]
