# Generated by Django 4.2.7 on 2024-01-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0009_ingrediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_ed', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_ed', models.CharField(max_length=100)),
                ('procedimiento_ed', models.CharField(max_length=500)),
                ('ingrediente_ed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.ingrediente')),
                ('platillo_ed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Facturacion.platillo')),
            ],
        ),
    ]
