from django.urls import path
from . import views

urlpatterns=[
    path('',views.listadoProvincias),
    path('guardarProvincia/',views.guardarProvincia),
    path('eliminarProvincia/<id_ed>' ,views.eliminarProvincia),
    path('editarProvincia/<id_ed>' ,views.editarProvincia),
    path('procesarActualizacionProvincia/', views.procesarActualizacionProvincia),
    path('listadoClientes/',views.listadoClientes),
    path('eliminarCliente/<id_ed>' ,views.eliminarCliente),
    path('listadoClientes/guardarCliente/',views.guardarCliente),
    path('editarCliente/<id_ed>' ,views.editarCliente),
    path('procesarActualizacionCliente/', views.procesarActualizacionCliente),
    path('listadoPedidos/',views.listadoPedidos),
    path('eliminarPedido/<id_ed>' ,views.eliminarPedido),
    path('guardarPedido/',views.guardarPedido),
    path('editarPedido/<id_ed>' ,views.editarPedido),
    path('procesarActualizacionPedido/', views.procesarActualizacionPedido),
    path('listadoTipos/',views.listadoTipos),
    path('eliminarTipo/<id_ed>' ,views.eliminarTipo),
    path('guardarTipo/',views.guardarTipo),
    path('editarTipo/<id_ed>' ,views.editarTipo),
    path('procesarActualizacionTipo/', views.procesarActualizacionTipo),
    path('listadoPlatillos/',views.listadoPlatillos),
    path('eliminarPlatillo/<id_ed>' ,views.eliminarPlatillo),
    path('guardarPlatillo/',views.guardarPlatillo),
    path('editarPlatillo/<id_ed>' ,views.editarPlatillo),
    path('procesarActualizacionPlatillo/', views.procesarActualizacionPlatillo),
    path('listadoDetalles/',views.listadoDetalles),
    path('eliminarDetalle/<id_ed>' ,views.eliminarDetalle),
    path('guardarDetalle/',views.guardarDetalle),
    path('editarDetalle/<id_ed>' ,views.editarDetalle),
    path('procesarActualizacionDetalle/', views.procesarActualizacionDetalle),
    path('listadoIngredientes/',views.listadoIngredientes),
    path('eliminarIngrediente/<id_ed>' ,views.eliminarIngrediente),
    path('guardarIngrediente/',views.guardarIngrediente),
    path('editarIngrediente/<id_ed>' ,views.editarIngrediente),
    path('procesarActualizacionIngrediente/', views.procesarActualizacionIngrediente),
    path('listadoRecetas/',views.listadoRecetas),
    path('eliminarReceta/<id_ed>' ,views.eliminarReceta),
    path('guardarReceta/',views.guardarReceta),
    path('editarReceta/<id_ed>' ,views.editarReceta),
    path('procesarActualizacionReceta/', views.procesarActualizacionReceta),

]
